// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXJz9n_ParJd7Fw86wXwaOa6bwmReIJvA',
    appId: '1:296294113229:web:559c8e91ec556c9af32e84',
    messagingSenderId: '296294113229',
    projectId: 'tugaskakgem4',
    authDomain: 'tugaskakgem4.firebaseapp.com',
    storageBucket: 'tugaskakgem4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9wkzcpQjfvDfHGk3FETgfqVgRHV5lVxE',
    appId: '1:296294113229:android:03641888923680c4f32e84',
    messagingSenderId: '296294113229',
    projectId: 'tugaskakgem4',
    storageBucket: 'tugaskakgem4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0iFFhxdADGGvSDDh3MHkKYOxCMTk5qw',
    appId: '1:296294113229:ios:3a4f0d17dfda4dbff32e84',
    messagingSenderId: '296294113229',
    projectId: 'tugaskakgem4',
    storageBucket: 'tugaskakgem4.firebasestorage.app',
    iosBundleId: 'com.example.prak42200016103Abdisetiawan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0iFFhxdADGGvSDDh3MHkKYOxCMTk5qw',
    appId: '1:296294113229:ios:3a4f0d17dfda4dbff32e84',
    messagingSenderId: '296294113229',
    projectId: 'tugaskakgem4',
    storageBucket: 'tugaskakgem4.firebasestorage.app',
    iosBundleId: 'com.example.prak42200016103Abdisetiawan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXJz9n_ParJd7Fw86wXwaOa6bwmReIJvA',
    appId: '1:296294113229:web:2c5266ed103df274f32e84',
    messagingSenderId: '296294113229',
    projectId: 'tugaskakgem4',
    authDomain: 'tugaskakgem4.firebaseapp.com',
    storageBucket: 'tugaskakgem4.firebasestorage.app',
  );
}
